spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  sql:
    init:
      mode: always
      continue-on-error: true
  mvc:
    format:
      date-time: iso
      date: iso
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
# context path config
server:
  servlet:
    context-path: /api/v1
app:
  name: "\"The Mood\""
  reset-password-url: ${VITE_API_BASE_URL:base_url}/dashboard/auth/reset-password
  # cache expiration period is in minutes
  cache-expiration: 15
